### ISSUE TITLE
`Image` and `ImageSource` enhancements

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10147]
## What would you like to be added:

- [ ] [Refactoring] `Image` and `ImageSource` are using very different approaches for opening image sources between different targets (especially netstd vs mobile)
- [ ] [Refactoring] Unify implementation of various concrete `ImageSource` types
- [ ] [Perf] `ImageSource` is sometimes unnecessarily re-read from source even though it is not necessary
- [ ] [Perf] Setting the same `ImageSource` instance in multiple `Image` elements should not cause repeated load
- [ ] [Bug] Cancellation of image opening in progress should be implemented reliably
- [ ] [Bug] Cancellation token is ignored in some flows
- [ ] Ensure `ImageOpened` and `ImageFailed` are triggered correctly on all targets
- [ ] Ensure switching between source types is reliable (even different `ImageSource` types)

## For which Platform:

All

**Comment by MartinZikmund** [comment]
Still relevant

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** This is an epic/tracking issue for multiple Image and ImageSource refactoring tasks, not a single bug that can be reproduced with a code sample or test.
