### ISSUE TITLE
Control leaks roundup

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10309]
### Current behavior

This issue collects controls which are currently leaking on various platforms in the `When_Add_Remove` runtime test:

- [x] `Microsoft.UI.Xaml.Controls.AnimatedIcon` (WASM, Skia)
- [x] `Microsoft.UI.Xaml.Controls.BreadcrumbBar` (WASM, Skia)
- [x] `Microsoft.UI.Xaml.Controls.Expander` (WASM, Skia)
- [ ] `Microsoft.UI.Xaml.Controls.NavigationView` (WASM, Skia)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment]
Re-opening for NavigationView leak.
