### ISSUE TITLE
SkiaSharp Support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1116]
This issue is a meta issue for the tracking of the SkiaSharp support for Uno in general, and WebAssembly specifically.

- [ ] Improve support for additional codecs
- [ ] Add support for WebAssembly WebGL canvas https://github.com/mono/SkiaSharp/issues/876
- [ ] Skia m78 update

- [ ] Validate the support for all known methods with the mono-wasm interpreter https://github.com/nventive/Uno/issues/1131
- [x] Publish `Uno.SkiaSharp.Wasm` and `Uno.SkiaSharp.Views` packages
- [x] Add support for Wasm AOT
- [x] Add support for Uno.SkiaSharp.Extended https://github.com/mono/SkiaSharp/issues/876

Fixes https://github.com/nventive/Uno/issues/1070

**Comment by ghuntley** [comment]
See also https://platform.uno/skiasharp-support-for-webassembly-via-uno-platform/ for a status update.

**Comment by EisenbergEffect** [comment]
Just thought I'd check in here and see how things are going. I'm very interested in pure C#+Skia. It looks like the WebGL issue hasn't progressed since June. Can anyone provide a bit of a status report? Thanks!

**Comment by jeromelaban** [comment]
Hi @EisenbergEffect, thanks for asking! The WebGL update is still on the roadmap, we've announed it at UnoConf for future work.

At this time, the bulk of the work is stabilizing the SkiaSharp support for Wasm using software rendering, and [there was an update today](https://github.com/unoplatform/Uno.SkiaSharp/pull/13) that includes a lot of changes made for the past few months in the official SkiaSharp repo.

**Comment by EisenbergEffect** [comment]
@jeromelaban Thanks for the update. Please ping this issue when WebGL rendering drops. I'd love to give it a try. I've been using CanvasKit WebGL with TypeScript quite a bit this year and I'd like to compare the experience and performance to an equivalent C# implementation of my work.

**Comment by mattleibow** [comment]
It is coming folks!!! Very soon!!!

Progress is here: https://github.com/mono/SkiaSharp/pull/1333

_Just_ got the WebGL views to work!

**Comment by mattleibow** [comment]
Just more info, the Uno views for Android, iOS and macOS are already out: https://www.nuget.org/packages/SkiaSharp.Views.Uno

This is just the raster/CPU views at this time. GPU/OpenGL views are coming soon. Working on getting the WASM raster out first.

**Comment by jeromelaban** [comment]
This issue can now be closed as the support is now being added in the official SkiaSharp repo.

@mattleibow I'll make a PR to add support for Uno 3.0 soon.

**Comment by EisenbergEffect** [comment]
@jeromelaban Would you mind clarifying status and capabilities a bit more please? For example, is it now possible to write C# Skia code and compile to WASM? Can it be done with "vanilla" C# and WASM builds or is Uno required? Is it raster only or GPU?

**Comment by jeromelaban** [comment]
On Wasm, it is possible to use SkiaSharp with Uno.Wasm.Bootstrap projects (vanilla, in some sense), as well as full Uno projects using `SKXamlCanvas`. The implementation provided in the official repo supports both raster and GPU.

Note that at this point, Uno does not yet support using Skia as a rendering backend.
