### ISSUE TITLE
MediaPlayer WebAssembly

### ISSUE THREAD

**Issue by rafael-rosa-knowcode** [unoplatform/uno#11967]
This issue is an epic to the support for MediaPlayerElement on WebAssembly.

## Blocking issues
- [x] #12531
- [ ] #12533
- [ ] #12535
- [x] WebAssembly fullscreen is not working property
- [x] The transport control flickers when clicking any buttons - PR: https://github.com/unoplatform/uno/pull/12372
- [x] https://github.com/unoplatform/uno/issues/12437
- Migrate [this table](https://docs.google.com/spreadsheets/d/135nS-P1XeaLVnTvtDl69lDzAfXcGHuN8-RpLdabhmD0/edit#gid=0) to a markdown table in this issue.
- We need to take the table to the docs 
- - https://platform.uno/docs/articles/controls/MediaPlayerElement.html
- - https://github.com/unoplatform/uno/blob/master/doc/articles/controls/MediaPlayerElement.md
- But we need to finish the tests for each features and Media formats
- [x] https://github.com/unoplatform/uno/issues/12350 - PR https://github.com/unoplatform/uno/pull/12372

 ## Gallery samples issues
 - [x] (Rafael) https://github.com/unoplatform/uno/issues/12330
 	^ PR: https://github.com/unoplatform/uno/pull/12398
 - [ ] (Agnès) https://github.com/unoplatform/uno/issues/12331
 - [ ] (Agnès) https://github.com/unoplatform/uno/issues/12332
 - [x] (Xiaoy) https://github.com/unoplatform/uno/issues/12344
 	^ PR: #12440
 - [x] (Rafael) https://github.com/unoplatform/uno/issues/12352
 	^ PR: https://github.com/unoplatform/uno/pull/12416
 - [x] (Rafael) https://github.com/unoplatform/uno/issues/12338
 - [x] (Rafael) https://github.com/unoplatform/uno/issues/12341
 - [x] (Xiaoy) https://github.com/unoplatform/uno/issues/12333
 	^ PR: #12440
 - [x] (Xiaoy) https://github.com/unoplatform/uno/issues/12335
 	^ PR: #12440
 - [x] (Rafael) https://github.com/unoplatform/uno/issues/12499 - ^ PR: #12500 
 
## Future Features
- [ ] (Rafael) https://github.com/unoplatform/uno/issues/12336 - PR: https://github.com/unoplatform/uno/pull/12404
- [ ] https://github.com/unoplatform/uno/issues/12337
- [ ] https://github.com/unoplatform/uno/issues/12394
- [ ] ZoomButton need to show all option - Aspect - https://learn.microsoft.com/en-us/xamarin/community-toolkit/views/mediaelement
- [ ] Repeat show if true or false: show different icon or border state?
- [ ] FastRewind or FastForward need to show the rate? (1x, 1.25x or 3x, etc)
- [ ] Download option
- [ ] Speed
- [x] Picture-in-picture - Like https://www.w3schools.com/html/html5_video.asp
- [ ] Update the Visual of the Wasm to look like the Android (Pixel Perfect)
- [ ] Make the Media run playlist (Files m3u8) (Using [VideoJS](https://videojs.com/))
- [ ] Make the style customizable
- [ ] Should we set a max (or min for rewind)?
 - [ ] Update the Visual of the Wasm to look like the Android (Pixel Perfect)
 - [ ] Make the Media run playlist (Files m3u8) (Using [VideoJS](https://videojs.com/))

**Comment by rafael-rosa-knowcode** [comment]
New Issues

 - [ ] Update the Visual of the Wasm to look like the Android (Pixel Perfect)
 - [ ] Make the Media run playlist (Files m3u8) (Using [VideoJS](https://videojs.com/))
 - [ ] Make the style customizable
