### ISSUE TITLE
.NET 8 Support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11978]
- [ ] Uno.Wasm.Bootstrap update to latest .NET 8 preview
- [x] https://github.com/unoplatform/uno/issues/11977
- [ ] Update to C# 12
- [ ] Merge all nuspec props/targets in one buildtransitive folder
