### ISSUE TITLE
Samples App Canaries

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1312]
Create dev branch Canaries for the following samples/demo apps:

- [x] https://github.com/unoplatform/calculator
- [x] https://github.com/unoplatform/Uno.Playground
- [x] https://github.com/nventive/Uno.Xaml-Controls-Gallery
- [x] https://github.com/unoplatform/Uno.WindowsCommunityToolkit
- [ ] https://github.com/nventive/Uno.Telerik.UI-For-UWP
- [ ] https://github.com/nventive/Uno.WindowsStateTriggers
- [ ] https://github.com/nventive/Uno.BenchmarkDotNet
- [ ] https://github.com/nventive/Uno.RoslynQuoter
- [ ] https://github.com/nventive/Uno.RayTraceBenchmark
