### ISSUE TITLE
Support for `KeyboardAccelerators`

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#13341]
## What would you like to be added:

Handled and Element properties from KeyboardAcceleratorInvokedEventArgs are not implemented in Uno.

## Why is this needed:

Useful when adding keyboard accelerators to an app; WinUi/UWP parity

## Parts

- [x] #17129
- [ ] #17133
- [x] `TabView` support for Keyboard Accelerators
- [ ] #17132
- [x] `Button` and `ButtonBase` support for Keyboard Accelerators
- [ ] #17134
- [ ] #17131
- [ ] https://github.com/unoplatform/uno/issues/14416
- [x] https://github.com/unoplatform/uno/issues/15195
- [ ] #17135
- [ ] Ensure keyboard accelerators which are no longer alive are properly cleaned up from XAML root
- [ ] Avoid registering never touched KA collections (`IsEffectiveValueInSparseStorage`)

## For which Platform:

- [x] WebAssembly
- [x] Android
- [x] iOS
- [x] macOS (AppKit)
- [x] Mac Catalyst
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Linux Framebuffer
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates
