### ISSUE TITLE
Ship hotfixes for the Uno Solution Template to the Visual Studio gallery

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1381]
## What would you like to be added:

Ship the following hotfixes for the Uno Solution Template to the Visual Studio gallery when they are merged:

- [x] Android does not compile due to invalid filenames - https://github.com/unoplatform/uno/issues/1364
- [x] iOS does not compile due to deployment target not being defined - https://github.com/unoplatform/uno/issues/1377
- [ ] Make the .NET Core 2.2 SDK requirement for WebAssembly more obvious - https://github.com/unoplatform/uno/issues/1376

## Why is this needed:

File -> New Application should just work and put people on the path to success by default ✨

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [x] Solution Templates

**Comment by ghuntley** [comment]
Hotfixes have been PR'ed into Batman stable.
