### ISSUE TITLE
[Epic] Layout & Clipping issues

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#2603]
This is an _epic_ issue for layout & clipping issues.

* [x] https://github.com/unoplatform/uno/issues/652 **Clipping does not support wider than control itself**
  * [X] Fix for iOS / PR https://github.com/unoplatform/uno/pull/2481
  * [X] Fix for Android / PR https://github.com/unoplatform/uno/pull/2481
  * [ ] Fix for Wasm
* [ ] https://github.com/unoplatform/uno/issues/1885 **Grid with MinWidths summing to greater than container Width isn't clipped**
  * [ ] Fix for iOS
  * [ ] Fix for Android
  * [X] Fix for Wasm
* [x] [WASM] Clipping issue when a child is transformed #2514
* [X] https://github.com/unoplatform/uno/issues/2397
* [x] https://github.com/unoplatform/uno/issues/2541 **HorizontalAlignement issue when image is inside a button** - Android
  * internal: https://nventive.visualstudio.com/Umbrella/_workitems/edit/172832
* [x] https://github.com/unoplatform/uno/issues/2542 **Stretched filled ellipse not displaying** / iOS
  * internal: https://nventive.visualstudio.com/Umbrella/_workitems/edit/171681
  * Fix PR: https://github.com/unoplatform/uno/pull/2608
* [x] https://github.com/unoplatform/uno/issues/2547 **Stretched stroked Ellipse isn't correctly centered inside a Grid** / Android
  * internal: https://nventive.visualstudio.com/Umbrella/_workitems/edit/173232
  * Fix PR: https://github.com/unoplatform/uno/pull/2608
* [x] https://github.com/unoplatform/uno/issues/2430 **The space between the text and the clear button is too wide** / iOS
* [x] https://github.com/unoplatform/uno/issues/2450 **RadioButton adds extra padding**
  * [x] internal: https://dev.azure.com/nventive/Umbrella/_workitems/edit/170847 **A white line is displayed under the header** / iOS + Android
  * [x] Fix for iOS / PR https://github.com/unoplatform/uno/pull/2481
  * [x] Fix for Android / PR https://github.com/unoplatform/uno/pull/2481
* [x] https://github.com/unoplatform/uno/issues/2550 **The Top Margin of the Textbox is not applied**
  * [x] Fix for iOS / PR https://github.com/unoplatform/uno/pull/2481
  * [x] Fix for Android / PR https://github.com/unoplatform/uno/pull/2481
* [ ] https://nventive.visualstudio.com/Umbrella/_workitems/edit/165540 **White line at bottom of screen** / Android
* [x] https://nventive.visualstudio.com/Umbrella/_workitems/edit/168809 **Extra blank space below list** / Android
* [x] https://nventive.visualstudio.com/Umbrella/_workitems/edit/168937 **Dark background has white space at the bottom** / iOS + Android
* [x] https://github.com/unoplatform/uno/issues/2607 **ComboBoxes regression: down arrow misaligned** / iOS + Android
  * [x] Fix for iOS
  * [x] Fix for Android
* [x] https://github.com/unoplatform/uno/issues/2703 [iOS] Scrollviewer padding is incorrectly clipping content
* [x] https://github.com/unoplatform/uno/issues/2705 [iOS] TextBox with Height set is cut off
* [x] https://dev.azure.com/nventive/Umbrella/_workitems/edit/175742 **Button is clipped** / Android
* [x] https://dev.azure.com/nventive/Umbrella/_workitems/edit/175740 **Problems with animations** / Android

**Comment by Youssef1313** [comment]
https://github.com/unoplatform/uno/pull/18261/ should be the killer for this epic, hopefully.

**Comment by MartinZikmund** [comment]
Only relevant to native renderer, works correctly in Skia targets, closing.
