### ISSUE TITLE
Support for `MediaPlayerElement`/`MediaPlayer`

### ISSUE THREAD

**Issue by sonnemaf** [unoplatform/uno#2642]
## What would you like to be added:
Windows.UI.Xaml.Controls.MediaPlayerElement and/or Windows.Media.Playback.MediaPlayer

## Why is this needed:
I'm currently converting an UWP game (Minesweeper 10) to Uno. This game should play sounds. I would love to play them using an MediaPlayerElement or MediaPlayer.

I use the following SoundHelper to play my sounds. It works currently in UWP only.

### Support issues

- [ ] Captions support unoplatform/uno#4636
- [ ] DRM support unoplatform/uno#4637
- [ ] Playback speed other controls unoplatform/uno#4638
- [ ] Real-time playback unoplatform/uno#4445
- [x] [WASM] Add support for MediaPlayerElement https://github.com/unoplatform/uno/issues/11967
- [x] Skia support https://github.com/unoplatform/uno/issues/12240

#### All targets

- [x] https://github.com/unoplatform/uno/issues/12510
- [x] https://github.com/unoplatform/uno/issues/12331
- [x] https://github.com/unoplatform/uno/issues/12332
- [x] https://github.com/unoplatform/uno/issues/12336
- [ ] https://github.com/unoplatform/uno/issues/12337
- [x] https://github.com/unoplatform/uno/issues/12333
- [x] https://github.com/unoplatform/uno/issues/12335
- [x] https://github.com/unoplatform/uno/issues/12338
- [x] https://github.com/unoplatform/uno/issues/12341
- [x] https://github.com/unoplatform/uno/issues/12344
- [x] https://github.com/unoplatform/uno/issues/12352
- [x] https://github.com/unoplatform/uno/issues/12574
- [x] https://github.com/unoplatform/uno/issues/12649
- [x] https://github.com/unoplatform/uno/issues/12650
- [x] https://github.com/unoplatform/uno/issues/12651
- [x] https://github.com/unoplatform/uno/issues/12696

#### iOS/Android
- [ ] https://github.com/unoplatform/uno/issues/12396
- [ ] https://github.com/unoplatform/uno/issues/12346
- [x] https://github.com/unoplatform/uno/issues/12659

#### Android

- [ ] https://github.com/unoplatform/nventive-private/issues/451
- [ ] https://github.com/unoplatform/uno/issues/3112
- [x] https://github.com/unoplatform/uno/issues/12661

#### iOS
- [x] https://github.com/unoplatform/uno/issues/12343
- [x] https://github.com/unoplatform/uno/issues/12347
- [ ] https://github.com/unoplatform/Uno.Gallery/issues/875

#### Mac Catalyst
- [x] https://github.com/unoplatform/uno/issues/12663

#### Wasm/Skia
- [x] https://github.com/unoplatform/uno/issues/12394
- [x] https://github.com/unoplatform/uno/issues/12664

#### Wasm/iOS
- [x] https://github.com/unoplatform/uno/issues/12660

#### Wasm

- [x] https://github.com/unoplatform/uno/issues/12535
- [x] https://github.com/unoplatform/uno/issues/12350
- [x] https://github.com/unoplatform/uno/issues/12330
- [x] https://github.com/unoplatform/uno/issues/12653
- [ ] https://github.com/unoplatform/uno/issues/12665
- [ ] https://github.com/unoplatform/uno/issues/17771

#### Skia
- [ ] https://github.com/unoplatform/uno/issues/12692

## Example

```
using System;
using Windows.Media.Core;
using Windows.UI.Xaml.Controls;

namespace Minesweeper.Helpers {

    static class SoundHelper {

        public static MediaPlayerElement Player { get; set; } = new MediaPlayerElement();

        public static bool IsMuted { get; set; }

        public static void Play(Sound sound, double volume = 1D) {
            if (!IsMuted) {
                switch (sound) {
                    case Sound.Gameover:
                        Player.Source = MediaSource.CreateFromUri(new Uri("ms-appx:///Assets/Sounds/Yeah.wav"));
                        break;
                    case Sound.Explode:
                        Player.Source = MediaSource.CreateFromUri(new Uri("ms-appx:///Assets/Sounds/Explode.mp3"));
                        break;
                    default:
                        break;
                }
                Player.MediaPlayer.Volume = volume;
                Player.MediaPlayer.Play();
            }
        }

    }

    public enum Sound {
        Gameover,
        Explode,
    }
}
```

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment]
If I understand correctly, neither `wav` nor `mp3` work?

**Comment by SuperJMN** [comment]
My team at Fluendo would absolutely need video playing capabilities to consider Uno Platform to make the new version of our product.

**Comment by MCAleckson** [comment]
My dev team really needs the ability to play and control a video on a WASM page.  We've implemented two complete UNO to AWS serverless mobile apps to great success, and now turn to implement a WASM app using the underlying code and can't open a media player on a page.  Please tell me I've missed something, and we can indeed do this via some mechanism we haven't unearthed (trying now to get the Ch.9 Javascript method working). Thank you.

**Comment by sasakrsmanovic** [comment]
Hello @MCAleckson  - that sounds fantastic. I'd love to get in touch to see how we can help and how can we scope your request. Would you please reach out to sasha@platform.uno please?

**Comment by MCAleckson** [comment]
I will  - thank you very much!

**Comment by XeonG** [comment]
Should be a priority on getting a working video/audio media playback component in UNO.. disappointing really.

**Comment by jeromelaban** [comment]
@XeonG the MediaPlayer works on iOS/Android. Are you looking for WebAssembly? Note that we prioritize work based on our clients' priorities.

**Comment by XeonG** [comment]
I'm looking for all platform support like the rest of UNO stuff, mainly Desktop(Windows/Linux)/Android/Web browser.. a media audio/video example that works for them all..

Not looking for fancy streaming codec support... just whatever video codec works across all and even then I dont' mind having to use different codecs for a particular platform.. but yeah media player component that works on them all with some level of customizing the player controls? hope to see it someday, seems even MAUI has failed on providing such a thing yet so guess its not a high priority.

**Comment by jeromelaban** [comment]
Thanks for the details. The good thing is that the non-platform-specific code already allows for customization of the UI, and what's missing the integration of the video playback itself.

WebAssembly is reachable to a certain extent (we used a [very basic one here](https://github.com/unoplatform/Uno.Ch9/blob/master/src/Ch9/Ch9.Wasm/HtmlMediaPlayer.cs)) within the limits of the browser, but Skia is a bit more difficult. It requires compositing with Skia, with the integration of platform specific libraries, such as ffmpeg or libvlc, but we have not gone that far yet.

**Comment by MartinZikmund** [comment]
@Jen-Uno many of the issues in the description can be parented to this epic

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** This is a meta tracking epic for `MediaPlayerElement`/`MediaPlayer` support with many sub-issues (most already resolved). `MediaPlayerElement` has been implemented and is tracked by specific sub-issues. If there are remaining broken scenarios, please refer to the individual open sub-issues.
