### ISSUE TITLE
[Epic] Add support for FileSavePicker

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#3215]
## What would you like to be added:

Support for [FileSavePicker](https://docs.microsoft.com/en-us/uwp/api/windows.storage.pickers.filesavepicker?view=winrt-18362) for all platforms

## Child issues

- [x] **Android** - [#5230]
- [x] **iOS** - [#5229]
- [x] **macOS** - [#5231]
- [x] **WASM** - [#5232]
- [ ] **Skia GTK** - [TBD]
- [x] **Skia WPF** - [#3215]
- [ ] **Skia Tizen** - [TBD]

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by pkar70** [comment]
Adding FileSave to my FileOpen (for Android, #2896) would be very simple. But I have no time this week.

**Comment by MartinZikmund** [comment]
I have `FolderPicker` for macOS, is that also in the works or not?

**Comment by christosk92** [comment]
@MartinZikmund Are you still working on the FolderPicker? If not I could implement it.

**Comment by MartinZikmund** [comment]
@christosk92 I think I have a branch for it on my Mac, but haven't pushed it yet, I will check later. Not sure if @alextrepa has macOS folder picker started or done yet? I can provide my branch if not. But @christosk92 there are still file open and file save pickers, so I think you can take any of those two 👌👌.

**Comment by christosk92** [comment]
Cool! Seems like NSOpenPanel is pretty easy to implement. I've been already using it in one of my applications. I'll port it over to Uno. 
Cheers!

**Comment by alextrepa** [comment]
Hey, sorry I'm a little bit late, but I'm not working on this issue at the moment, so feel free to contribute to it ;).

**Comment by robloo** [comment]
I'm curious what the status is of this. I've seen the macOS PR which hasn't been merged yet. However, is there any other work on it for other platforms?

**Comment by MartinZikmund** [comment]
@robloo Android pickers are in PRs, just need to be cleaned up and finalized. iOS is not yet started. For macOS - I think FileOpenPicker is also to be started. WASM FolderPicker is in progress by Arlo Godfrey.

**Comment by MartinZikmund** [comment]
Closing this for now, only missing platforms are GTK and Tizen.
