### ISSUE TITLE
Epic: Routed Events improvements

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#322]
Missing tasks for RoutedEvents:

- [x] Don't systematically make handled events bubble up just in case an ancestor used `AddHandler(..., handledEventsToo: true)`
- [ ] Implement a WPF-inspired `internal virtual RoutedEventArgs.InvokeEventHandler(Delegate handler, object target)` to avoid switch cases in `UIElement.InvokeHandler`
- [x] Properly implement `Tapped` and `DoubleTapped` on Wasm
- [ ] Add support for` RemoveHandler` on Wasm
- [x] Make events bubble up on the managed side instead of the native side
- [ ] Test more throughly advanced scenario

**Comment by yowl** [comment]
this would be useful as isnt Tapped the one thats needed for Button's Command to work,e.g. `Command="{Binding OkCommand}"`?

**Comment by jeromelaban** [comment]
@yowl button commands are already implemented. Are you having an issue with that ?

**Comment by yowl** [comment]
Was another UserControl problem, I changed to ContentControl and its fine.  Saw the tapped not supported message in the console and incorrectly thought that was my problem.
