### ISSUE TITLE
[Epic] Controls initialization sequence

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#3519]
# Epic issue - Controls initialization sequence
This issue will try to regroup the following ones:
* #2895 Loading, Loaded & Unloaded events are called too early
* #2769 [Android] LayoutUpdated may be invoked twice
* #1763 [Wasm] Loaded even is raised too early
* #1478 Page.NavigatedTo is invoked after Page.Loaded
* #1863 Frame.Navigated and page's OnNavigatedTo fire in a different order on android than on uwp.
  * There's an unmerged PR for this one: #2008
* #190 Control templates are applied too early
* #4550 ContentDialog not appearing
* ScrollViewer performance https://github.com/unoplatform/uno/pull/4331 (collapsed items are being measured)
* ContentControl Content DataContext is incorrect on macOS https://github.com/unoplatform/uno/issues/4626
* x;Bind not working on navigation events https://github.com/unoplatform/uno/issues/2666
* NavigationView items are not rendered properly https://github.com/unoplatform/uno/issues/4689
* FrameworkElements in Resources are not loaded #5208
* Popups layout events https://github.com/unoplatform/uno/issues/5404
* TabView items Loaded event is raised too early https://github.com/unoplatform/uno/issues/5838
* https://github.com/unoplatform/uno/issues/7001
* https://github.com/unoplatform/uno/issues/7531
* https://github.com/unoplatform/uno/issues/13019

## Sequence of events on UWP

Lets suppose we have 2 controls in a direct parent/child relationship (on the logical tree) called `outer` and `inner`. Those 2 controls are created at the same time from the same XAML file like this:

``` xml
<Grid DataContext="myContext">
    <OuterControl x:Name="outer" Style="{StaticResource OuterControlStyle}">
        <OuterControl.Content>
            <InnerControl x:name="inner" Style="{StaticResource InnerControlStyle}" />
        </OuterControl.Content>
    </OuterControl>
</Grid>
```

 Here's the sequence of the initialization of those controls on UWP:

1. `outer` receive `DataContextChanged` event
2. `outer` gets assignments for all setters from `OuterControlStyle`  -- note: templates are not materialized yet
3. `outer` receive `Loading` event
4. `outer` control template gets materialized
5. `outer` gets called for `ApplyTemplate()`
6. `outer` gets called for `MeasureOverride()`. Calling `base.MeasureOverride()` will call:
    a. `inner` receive `DataContextChanged` event
    b. `inner` gets assignments for all setters from `InnerControlStyle`
    c. `inner` receive `Loading` event
    d. `inner` control template gets materialized
    e. `inner` gets called for `ApplyTemplate()`
    f. `inner` gets called for `MeasureOverride()`
7. `outer` gets called for `ArrangeOverride()`. Calling `base.ArrangeOverride()` will call:
   a. `inner` gets called for `ArrangeOverride()`
8. `outer` receive the `SizeChanged` event
9. `inner` receive the `SizeChanged` event
10. `outer` receive the `Loaded` event
11. `inner` received the `Loaded` event

## Affected platform(s):

- iOS
- Android
- WebAssembly
- macOS [not tested yet]

## Problems
1. [ ] On UWP, `OnApplyTemplate()` is called during the first _measure_ phase (step 6). Currently on Uno (all platforms) it's called synchronously with the assignation to the `Template` (ControlTemplate) property (step 4)
2. [ ] On Wasm, `inner` receives twice t he `Loading` event
3. [ ] On Uno (all platforms), the `DataContextChanged` is raised synchronously with the assignation. Should be deferred to the first measure phase (6.a.)
4. [x] On Uno (all platforms), the control template gets materialized synchrnously during the `Template` assignation and `ApplyTemplate` is also called immediatly. They should be be deferred to the first _measure_ phase.  Or, at least, the call to `ApplyTemplate` should be deferred.
5. [ ] On iOS, the `inner` gets unloaded + reloaded after its template has been materialized
6. [ ] `Loading` should be raised on `outer` before `inner` (incorrect on iOS)
6. [ ] `SizeChanged` should be raised on `outer` before `inner` (correct only on iOS)
7. [ ] `SizeChanged` should be raised **BEFORE** the `Loaded` event for both `inner` & `outer` (all platforms)
8. [ ] `Loaded` should be raison on `outer` before `inner` (correct only on Android)

**Comment by MartinZikmund** [comment]
Controls initialization is now aligned on Skia
