### ISSUE TITLE
Add support for Date related controls

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#365]
## I'm submitting a...
- Feature

## Expected behavior
Support for:
- [ ] The `CalendarDatePicker` control (#3750)
- [X] The `DatePicker` control (https://github.com/unoplatform/uno/issues/1390) -> [PR 4956](https://github.com/unoplatform/uno/pull/4956)
- [ ] The `TimePicker` control (#5553)

## Environment
Nuget Package: 1.41.1

**Comment by robloo** [comment]
Please also include the `CalendarView` control

As discussed in #1933.

**Comment by DierkDroth** [comment]
@jeromelaban any chance to get the DatePicker prioritized?

**Comment by MartinZikmund** [comment]
Closing issue as each of the controls has their own specific one open (see description)
