### ISSUE TITLE
[Epic] Add support for FolderPicker

### ISSUE THREAD

**Issue by Arlodotexe** [unoplatform/uno#3916]
## What would you like to be added:
Support for the [FolderPicker](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.Pickers.FolderPicker?view=winrt-19041) on all platforms.

## Why is this needed:
So the API can be used cross platform.

## Child issues

- [x] **Android** - [#5227]
- [x] **iOS** - [#5226]
- [x] **macOS** - [#5228]
- [x] **WASM** - [#4447] - in progress (PR #4588)
- [ ] **Skia GTK** - [TBD]
- [ ] **Skia WPF** - [#5233]
- [ ] **Skia Tizen** - [TBD]

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by Arlodotexe** [comment]
Pasting my comment from [here](https://github.com/unoplatform/uno/issues/508), as its relevant.

> There is a [Native File System API](https://web.dev/native-file-system/) which is implemented in Chromium browsers, and can be enabled via a flag, though the [W3C spec](https://wicg.github.io/native-file-system/) is still marked as a Draft. Mozilla seems to be working on the spec as well ([see here](https://github.com/mozilla/standards-positions/issues/154)).
> 
> For early adopters, it could be worth adding FileOpenPicker support via this API. When the Native File System API is finalized, should the API interfaces change, they can be updated in Uno.
> 
> edit: Looking into it further, "Original trial" means you need to request a token from Google to use the API before it's ready. The token is locked to a specific origin, has a usage limit, and the entire feature will be disabled (e.g. they outright remove the flag) if used by more than 0.5% of all Chrome page loads. So it won't be feasible to add this for everyone in WASM right now.

**Comment by Arlodotexe** [comment]
Looks like the API has finished their origin trial and can be implemented.

However, it should be noted that this API still doesn't have a W3C standard and isn't on the standards track. Could be useful to interface through a JS library (if possible) for polyfills ([such as this one](https://web.dev/browser-nativefs/)).

**Comment by MartinZikmund** [comment]
Closing, only missing folder pickers are GTK, WPF and Tizen.
