### ISSUE TITLE
Skia Rendering Backend Support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#4309]
This issue is an epic that tracks opened issues and larger items to improve the Skia backend support, for Linux and other platforms.

- [ ] Improved TextBlock support
- [ ] TextBox support
- [ ] Keyboard events support
- [ ] DPI Scaling support
- [ ] Automated testing
- [ ] Compositor Thread
- [ ] Composition Animations support
- [ ] Acrylic brush support
- [ ] ReadyToRun support for x64, arm64
- [ ] Single file packaging
- [ ] Per layer runtime selection (Skia rendering + non-UI per platform)

**Comment by microhobby** [comment]
@jeromelaban, and maybe also @mattleibow, could you help me with some questions?

I think SkiaSharp runs with OpenGL/GPU graphics acceleration, so my question: today the render that we have in Gtk uses OpenGL/GPU? I did not find anything that could affirm this, in some tests I had a certain increase in the use of the GPU (maybe this increase is just from the Gtk shell), but when using in some Linux embedded systems with lower CPU power the performance is much worse,  seems that everything is being done in CPU. Looking at the code I didn't find anything creating the openGL context.

And the second question, if we are not using openGL/GPU in SkiaSharp for Gtk what would be the effort to implement this? (it would be easy, difficult, we already have something to base on ....)

**Comment by jeromelaban** [comment]
@microhobby at this point, the Uno implementation for the Skia backend uses a derivative of the SkiaSharp.Views GTK View which is using software rendering. There's no official OpenGL implementation of the GTK rendering, so we do no know the kind of effort would be needed to enable this. @mattleibow may know more.

In all cases, we have that on the backlog and we'll investigate it as part of the Linux support effort.

**Comment by mattleibow** [comment]
At this point, there was not much demand for GTK views so I just threw in this commented code. https://github.com/mono/SkiaSharp/blob/main/source/SkiaSharp.Views.Forms/SkiaSharp.Views.Forms.GTK/SKGLWidget.cs

It theoretically should be quite easy to use if we use the `GLWidget` from OpenTK. Not exactly sure the issue that I had... Might have been just the fact that there was a few assembly conflicts because Forms used to bundle its own copy in the nuget. But I think that changed.

Until I can get to it, someone could have a stab at this.

That code was also GTK 2 so may need adjusting. I also see that GLWidget seems to no longer be the thing: https://github.com/opentk/opentk/blob/3.x/src/OpenTK.GLWidget/GLWidget.cs Not sure if this is superseded by something better or they stopped supporting it. But, either way, this should not stop us from creating our own views. Most GL views now already have entirely custom setup for the GL context.

**Comment by mterwoord** [comment]
The issue needs adjusting  Keyboard events support (#4318) is already done.

**Comment by Leon99** [comment]
I'm curious about WASM. Is it in the scope of this epic? Is there a hope it will improve performance in browsers?

**Comment by jeromelaban** [comment]
@Leon99 we have in the backlog to work on adding a skia rendering backend for Wasm, though while it may improve the performance, it may also reduce compatibility for some features like accessibility, IME support or third party javascript integrations.

It will likely be a compromise. That being said, w.r.t performance, you can already take a look at Uno 3.8-dev bits, there are some pretty significant advances there.

**Comment by georgiuk** [comment]
Is the native view hosting doable in skia rendering, eg for WebView? What is the method to do it, rendering infront of skia canvas?

**Comment by jeromelaban** [comment]
@georgiuk overlays and compositing are two techniques we're investigating, but we're not there yet. Both techniques have their advantages and drawbacks (overlay makes compositing impossible, and threaded rendering jittery, while compositing can make pointers support somewhat difficult).

**Comment by lindexi** [comment]
Multi-Touch support for Skia WPF does not appear to have been added.

**Comment by ivanjx** [comment]
do we still need the gtk runtime to be installed separately with skia rendering backend?

**Comment by jeromelaban** [comment]
@ivanjx for now, this is still needed. We've made recent changes to make this dependency visible when the app is started.

Do you have a scenario where this is causing issues?

**Comment by ivanjx** [comment]
@jeromelaban i mean if the backend will be on skia why not just remove the gtk completely like in avalonia? the issue with gtksharp is that we need to install it separately rather than just including dlls like skiasharp.

**Comment by ivanjx** [comment]
is there more work for the webview control? the issue is closed but here it is still in the backlog list.

**Comment by jeromelaban** [comment]
@ivanjx which issues are you facing? WebView2 is there, but we may have missed something. If that's the case, make sure to open an issue, thanks!

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** This is a meta tracking epic for Skia backend improvements with a checklist of sub-issues. There is no specific broken behavior to reproduce — it tracks multiple features and improvements, many of which are already done.
