### ISSUE TITLE
[Epic] Add support for FileOpenPicker

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#508]
## I'm submitting a...

  
- Feature request

## Current behavior
The FileOpenPicker works on UWP, but not on any other platform.

## Expected behavior
The FileOpenPicker works an all platforms.

## Child issues

- [x] **Android** - #4016 (in progress)
- [x] **iOS** - #4027
- [x] **macOS** - #3890 (in progress)
- [x] **WASM** - #4028 (in progress)
- [ ] **Skia GTK** - #5268
- [x] **Skia WPF** - #5235 ✅
- [ ] **Skia Tizen** [TBD]

## Minimal reproduction of the problem with instructions
Simply make a call to the FileOpenPicker from Windows.Storage.Pickers.

## Environment
Affected platform(s):
- [X] iOS
- [X] Android
- [X] WebAssembly
- [x] Windows
- [ ] Build tasks

**Comment by mfe-** [comment]
Greetings, any news on this?

**Comment by ghuntley** [comment]
howdy @mfe-, we would accept a pull-request that implements this, even if it was a partial implementation for a single platform. I have set aside time to pair with folks like yourself to help with contributing features to the code base. Let me know if you are keen.

**Comment by mfe-** [comment]
Hi @ghuntley I'm afraid I don't know much about mono wasm and how the Uno platform works. As I'm still interested in this topic, I'm reading into it and let you know when I'm ready.

**Comment by FrancoisM** [comment]
This almost work on wasm:

```
function openFilePicker() {
    var input = document.createElement('input');
    input.type = 'file';
    input.accept = '.jpg, .png, .jpeg, .gif, .bmp, .tif, .tiff|image/*';
    input.onchange = e => {
        var file = e.target.files[0];
        var reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = readerEvent => {
            var content = readerEvent.target.result; // this is the content!
            console.log(content);
            input.dispatchEvent(new CustomEvent("fileSelectedEvent", { detail: content }));
            console.log("Sent");
        };
    };
    input.click();
}

private async void OnLogoButtonClicked(object sender, RoutedEventArgs e)
{
    this.RegisterHtmlCustomEventHandler("fileSelectedEvent", OnFileSelectedEvent, isDetailJson: false);
    WebAssemblyRuntime.InvokeJS("openFilePicker();");
}

private void OnFileSelectedEvent(object sender, HtmlCustomEventArgs e)
{
    Console.WriteLine("Received");
    //transofrm e.Detail from DataUrl to an image source
}
```

**Comment by FrancoisM** [comment]
Note: it's easier to directly set the html image src:
```
var image = document.getElementsByTagName("img")[0];
image.src = content;
```
The problem is that we need a mecanism to identify the correct image. Some tag that would be set in xaml and pass trough to html for example.

**Comment by FrancoisM** [comment]
Here we go 😄 

```
function openFilePicker(htmlId) {
    console.log(htmlId);
    var input = document.createElement('input');
    input.type = 'file';
    input.accept = '.jpg, .png, .jpeg, .gif, .bmp, .tif, .tiff|image/*';
    input.onchange = e => {
        var file = e.target.files[0];
        var reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = readerEvent => {
            var content = readerEvent.target.result; // this is the content!
            var imageDiv = document.getElementById(htmlId);
            var image = imageDiv.getElementsByTagName('img')[0];
            image.src = content;
        };
    };
    input.click();
}
```

**Comment by edparitor** [comment]
Is there a way to upvote this without creating more comments/items?

**Comment by pkar70** [comment]
It is implemented for Android, but not included in Uno. You have to make your own compilation, adding #2896.

**Comment by MartinZikmund** [comment]
Created separate issue for macOS implementation #3890.

**Comment by Arlodotexe** [comment]
There is a Native File System API which is implemented in Chromium browsers, and can be enabled via a flag, though the [W3C spec](https://wicg.github.io/native-file-system/) is still marked as a Draft. Mozilla seems to be working on the spec as well ([see here](https://github.com/mozilla/standards-positions/issues/154)).

For early adopters, it could be worth adding FileOpenPicker support via this API. When the Native File System API is finalized, should the API interfaces change, they can be updated in Uno.

**Comment by sjb-sjb** [comment]
Can we add FileSavePicker to this issue please? Should work at least on macOS, perhaps others.

**Comment by MartinZikmund** [comment]
Closing this for now, only GTK missing, which has an open issue.
