### ISSUE TITLE
[Epic] Animation for Android

### ISSUE THREAD

**Issue by dr1rrb** [unoplatform/uno#5586]
## What would you like to be added:
More performant animations on Android

## Why is this needed:
Fix multiple issues with current implementation, match the UWP behavior en enhance performance.

## For which Platform:
- [x] Android

## Anything else we need to know?
Related epic for WASM: https://github.com/unoplatform/uno/issues/3919

## Required features
- [x] Add independent compositor thread
- [ ] Capture current rendering of controls into `RenderNode`
- [ ] Update the `RenderTransformAdapter` to use those nodes
- [ ] Update the pointers dispatch to take care of the new transforms
- [ ] Implement the animations composition APIs
- [ ] Refactor XAML animations to use composition APIs

## Misc tasks and tests
- [ ] Validate the `CompositorThread` behavior when Android's `Activity` is re-created (https://github.com/unoplatform/uno/pull/5587#discussion_r604829345).

**Comment by MartinZikmund** [comment]
No longer relevant, improvements will be made for Skia renderer targets
