### ISSUE TITLE
Requested how-to articles

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#5703]
- [ ] Standardize formatting for all how-tos
 - [ ] How to integrate Cupertino theme
 - [ ] How to work with light/dark themes: https://github.com/unoplatform/uno/issues/4568
 - [ ] How to load image resources: https://github.com/unoplatform/uno/issues/3976
 - [ ] How to load text resources
 - [ ] How to use VisibleBoundsPadding
 - [ ] How to show a splashscreen on startup: https://github.com/unoplatform/uno/issues/5507
 - [ ] MSAL how-to is missing sample: https://github.com/unoplatform/uno/issues/5347
 - [ ] SignalR how-to is incomplete and should point to sample: https://github.com/unoplatform/uno/issues/5335
 - [ ] How-to implement deep-linking: https://github.com/unoplatform/Uno.Samples/issues/579
 - [ ] How to integrate SkiaSharp

**Comment by DevTKSS** [comment]
@MartinZikmund @Jen-Uno dont know if we keep this issue here and refresh the content, but for the `Load text resources` I would have some PR providing some content for this you could link 👍 
- https://github.com/unoplatform/uno.extensions/pull/2734 is adding text file specific functionallity to storage so we could select which lines of this text file we want, without having to write this functionality ourselfs 🚀 
- https://github.com/unoplatform/uno.extensions/pull/2710 is providing storage extension specific introductions and Getting Started content + links to other file management features Uno provides, while Storage Extension usage is our Go-To for those text files
- https://github.com/unoplatform/uno.extensions/pull/2824 adds How-To's to all available Storage Extension Methods + (commented) the sample for 2710

So I would guess, that would potentially fix this bulletpoint on this list above 🚀

**Comment by jeromelaban** [comment]
@DevTKSS thanks, this list is not related. You already have issues opened for those PRs, let's discuss on those specifically.

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** Documentation request for how-to articles.
