### ISSUE TITLE
Shadow enhancements

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6183]
## What would you like to be added:

Improving shadow support in Uno Platform

## Why is this needed:

🌑

## Checklist

- [ ] Update the `ElevatedView` with new, previously unsupported features
- [ ] Implement WCT `DropShadow` control to use `ElevatedView` in Uno to reduce friction for porting
- [ ] Implement the `.Shadow` property on WASM, Skia, and potentially iOS [#6362]
- [ ] Add support for `.Shadow` for templated `Controls` by injecting `ElevatedView`
- [ ] Add `ElevatedView` in place of `.Shadow` property on unsupported platforms in custom templates
- [ ] Add support for "Elevation" attached property on more targets
- [ ] https://github.com/unoplatform/uno/issues/7114

## Related issues

- [ ] [Gallery][Skia.GTK] Card- Shadow for "Elevated card with supporting content" is missing. #5879
- [ ] [Gallery][Skia.GTK]ElevatedView -The elevated line are missing for dp. #5863

## For which Platform:

All

**Comment by NVLudwig** [comment]
Here are the properties I would need to support Elevation across different design systems:
• Drop Shadow X, Y, offset position
• Shadow Size
• Shadow Spread
• Shadow Color
• Shadow Transparency 
 
 and ideally for better UX and Workflow:
 • Main light source control: as a user I can make a adjustment to one of the above properties and have it applied proportionally to the all Elevations in a project Theme 
 
 e.g.: 
 I change position, size, spread of the Shadow from "Main Light Source' in Elevation 24 dp then all other elevations (0, 1, 2, 3,4,6,9,12,18) also change their shadows proportionally.
 
 If I change Color or Alpha it should change exactly the same way in all elevations.
 
![Elevation Properties](https://user-images.githubusercontent.com/29584087/173090672-ea980669-bd98-4145-bd38-8e2d3b90ad0e.png)

**Comment by agneszitte-nventive** [comment]
Thanks for the recap list @NVLudwig

**Comment by agneszitte-nventive** [comment]
> and ideally for better UX and Workflow: • Main light source control: as a user I can make a adjustment to one of the above properties and have it applied proportionally to the all Elevations in a project Theme
> 
> e.g.: I change position, size, spread of the Shadow from "Main Light Source' in Elevation 24 dp then all other elevations (0, 1, 2, 3,4,6,9,12,18) also change their shadows proportionally.
> 
> If I change Color or Alpha it should change exactly the same way in all elevations.

Like we talked about it @MartinZikmund I think that this could be easily managed with a main Style that the others can be based on

**Comment by sakshi173** [comment]
The Elevated view is not properly visible for Gallery(WASM) and it is properly visible for Gallery(Skia.Gtk).
![Elevated view](https://user-images.githubusercontent.com/74563602/174883200-9006a5b1-b967-40cc-b85d-c543f6906c9e.png)
![Elevated view Skia](https://user-images.githubusercontent.com/74563602/174883210-3d6c205e-d3e8-472e-bdb9-8f0e51d7b81d.png)
