### ISSUE TITLE
[Epic] macOS support

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#626]
## I'm submitting a...
- Feature request

## Description
Known tasks :

- [x] Publish macOS nuget target
- [x] Document macOS build target
- [x] Package the Samples app
- [ ] Update the vsix templates to include a macOS target
- [x] Validate measure/arrange phases
- [x] Validate overall initial behavior
- [x] Uno Calc: add support for macOS (https://github.com/unoplatform/uno/issues/3103)
- [ ] Update the vsix templates to include a main Storyboard (https://github.com/unoplatform/uno/issues/3124)
- [x] Add support for Localization (https://github.com/unoplatform/uno/issues/3129)

## Structure
- [ ] Text rendering
- [x] Font size (too small) https://github.com/unoplatform/uno/pull/2926
- [ ] TextRendering performance
- [ ] XAML events WeakReference is collected too early
- [ ] RenderTransforms https://github.com/unoplatform/uno/issues/2971
- [ ] UI Testing support
- [ ] Key events (https://github.com/unoplatform/uno/issues/3167)

## Runtime Tests (non exhaustive list)
https://github.com/unoplatform/uno/issues/9282

## Controls
- [x] TextBox https://github.com/unoplatform/uno/pull/2926
- [ ] TextBox support for multiline and Enter key
- [ ] List Virtualization 
- [ ] ScrollViewer (unable to scroll UnitTests)
- [ ] GridView support
- [x] Shapes (https://github.com/unoplatform/uno/issues/2961)
- [x] Image support
- [x] PasswordBox support (https://github.com/unoplatform/uno/issues/3005)
- [x] CheckBox (https://github.com/unoplatform/uno/issues/3035)
- [ ] Popups / Flyouts
- [x] ComboBox (https://github.com/unoplatform/uno/issues/2972)
- [x] Slider
- [ ] Canvas
- [ ] ViewBox
- [ ] Native Button
- [ ] Native ToggleSwitch
- [ ] Native ProgressBar
- [ ] Native CheckBox
- [ ] Native ProgressRing
- [ ] CameraCaptureUI
- [ ] NavigationView
- [ ] Animations
- [x] DisplayInformation (https://github.com/unoplatform/uno/issues/2907)
- [x] MediaPlayer (https://github.com/unoplatform/uno/issues/3020)
- [x] Clipboard (https://github.com/unoplatform/uno/issues/2915)
- [x] WebView (https://github.com/unoplatform/uno/issues/2916)
- [ ] ScrollViewer.ChangeView (SetContentOffset, Zoom)
- [ ] VibrationDevice
- [ ] DisplayRequest
- [ ] MapControl

Related #66

**Comment by MartinZikmund** [comment]
Bringing this up as per Twitter conversation with @snickler, Andrew Hoefling and S Ravi Kumar.

**Comment by techierathore** [comment]
Thanks @MartinZikmund , I would love to join you guys and see how I can support.

**Comment by robloo** [comment]
@jeromelaban It seems Microsoft has now committed to supporting Catalyst with Xamarin in the .net 6 timeframe. I believe the lack of Catalyst support was the reason that the macOS backend in Uno had to make separate implementations/code-paths in several unwanted places.

As the macOS backend is also lacking is several areas of functionality and has many bugs, what is the future architecture of Uno in this space? I would think macOS support would essentially be on hold until .net 6 and either:

 1. Remove the separate backend for macOS and just use iOS/iPadOS apps targeting macOS. This should clean up a lot of Uno code and fill in gaps of functionality while fixing bugs. Apps will not be as heavily desktop oriented though.
 2. Pursue a Skia rendering backend for macOS like Win7 and Linux. Again, this cleans up a lot of code but you loose access to native controls and more advanced controls. (bad for the short term)

**Comment by jeromelaban** [comment]
For now, we're still going to maintain the macOS support that we currently have as there are many parts that shared with iOS (.NET 6 is still very far away) and customers need it, but Catalyst is definitely going to help streamline the development going forward.

**Comment by robloo** [comment]
Is there any need to re-evaluats this considering where macCatalyst support is today? On my end I'm going to prototype using an iOS app directly in macOS using the new Catalyst support. I expect functionality, performance and feature completeness is superior this way.

**Comment by jeromelaban** [comment]
`net6.0-maccatalyst` is not a complete replacement for `Xamarin.Mac`/`net6.0-macos`, because there are missing desktop-related APIs provided by AppKit, and the sandboxing works differently, iirc. That being said, Uno's Skia/GTK head works properly on macOS, so this is a head worth considering.

**Comment by robloo** [comment]
I'm glad Skia is working nicely on macOS now. My concern with Skia is the high number of unimplemented features compared to Android/iOS, not to mention the added difficulty embedding native controls. Performance was wonderful last I tried it though (which can't be said about macOS at this point).

I expect macCatalyst to have no more restrictions than iOS (so sandboxing and desktop-related APIs are no concern) and an iOS version will need to be completed next on my end. It should be a relatively straight-forward path to run on macCatalyst from here -- at least as a prototype. This seems to make the most sense considering where Uno is today in terms of feature completeness and performance on macOS. It's amazing that Uno provides three different options for getting an app to run on macOS!

**Comment by xperiandri** [comment]
As long as a lot of referenced issues were closed it may be worth updating the checkboxes to actual states, don't it?

**Comment by MartinZikmund** [comment]
This is no longer relevant, as we have a new macOS backend!
