### ISSUE TITLE
[Epic] WinUI 2.6

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6747]
Tracking support for WinUI 2.6 and related.

**Required**

- [x] Linker support to allow removing unused styles (V1 vs V2)
- [x] #6748
- [x] #6749
- [x] #6750
- [x] #6751
- [x] #5734  (discussion #6493)
- [x] #6614 
- [ ] #7021
- [x] Verify the new control styles on all targets
   - `MonochromaticOverlayPresenter` workaround

**Nice to have**

- [ ] Support for `BreadcrumbBar` (#6344)
- [ ] Support for `PipsPager` (#5149)
- [ ] Support for `ThemeShadow` (#6362)
  - Apply shadow to popups

**Comment by MartinZikmund** [comment]
No longer relevant
