### ISSUE TITLE
Update playground WCT samples

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8506]
Samples to add (create the playground links and paste those here):

- [x] WCT DockPanel https://playground.platform.uno/#5cc32ff4
- [x] WCT AlignmentGrid https://playground.platform.uno/#c82e4163
- [x] WCT FocusTracker https://playground.platform.uno/#aafbfcc4
- [x] WCT WrapPanel https://playground.platform.uno/#e8d41f42
- [x] WCT StaggeredLayout https://playground.platform.uno/#fa6efa90
- [x] WCT WrapLayout https://playground.platform.uno/#4ab14adc
- [x] WCT RadialProgressBar https://playground.platform.uno/#315b4396
- [x] WCT ColorPickerButton https://playground.platform.uno/#9de96045 (Works, but ColorPicker looks a bit glitched) 
- [x] WCT RangeSelector http://playground.platform.uno/#83e2d239
- [x] WCT TokenizingTextbox http://playground.platform.uno/#d3859705 (Seems to works, but is missing some c# code)
- [x] WCT BladeView http://playground.platform.uno/#e1a2ae64
- [x] WCT ConstrainedBox http://playground.platform.uno/#23441545
- [x] WCT Carousel https://playground.platform.uno/#fba96573 (Works, but not that well)
- [x] WCT GridSplitter http://playground.platform.uno/#f1baf71e (Missing some styling)
- [x] WCT HeaderedContentControl http://playground.platform.uno/#b72ec2c8
- [x] WCT HeaderedItemsControl http://playground.platform.uno/#e3ceb6d5
- [x] WCT LayoutTransformControl http://playground.platform.uno/#7b8dc03d (Issue with positioning probably due to RenderTransformOrigin)
- [x] WCT SwitchPresenter http://playground.platform.uno/#01368176
- [x] WCT DropShadowPanel https://playground.platform.uno/#38cac1e9 (Missing some style, Microsoft docs said it is soon to be removed)
- [x] WCT UniformGrid https://playground.platform.uno/#e0e5e38d
- [x] WCT ImageEx https://playground.platform.uno/#61c61ba7
- [x] WCT Menu http://playground.platform.uno/#0c874009 (Few bugs, probably missing some c# code)
- [x] WCT TabbedCommandBar http://playground.platform.uno/#917004f8
- [x] WCT Loading https://playground.platform.uno/#b9179530 (Doesn't diplay the ProgressBar element, might be missing some c# code for it to acutally do something)
- [x] WCT Radial Gauge http://playground.platform.uno/#3de6bebc (Doesn't respond well to inputs, the smaller the page or the gauge is, the worst it gets)
- [ ] WCT Markdown TextBlock https://playground.platform.uno/#dd488b4a (Doesn't display text)
- [ ] WCT DataGrid http://playground.platform.uno/#dbb404d5 (Unable to display data)
- [ ] WCT LoginButton, PeoplePicker and PersonView https://playground.platform.uno/#d8f96fd5 (missing support for CommunityToolkit.Graph.Uwp.Controls)
- [ ] WCT Eyedropper https://playground.platform.uno/#82a21564 (Not recognized by the playground)
- [ ] WCT ImageCropper https://playground.platform.uno/#1f45defb (Not recognized by the playground)
- [ ] WCT RichSuggestBox http://playground.platform.uno/#080136b4 (Not recognized by the playground)
- [ ] WCT AdaptiveGridView http://playground.platform.uno/#44c52fd6 (Doesn't display anything)
- [ ] WCT Expander http://playground.platform.uno/#08765d1a (Doesn't work, -Infinite size error in the console)
- [ ] WCT ListDetailsView http://playground.platform.uno/#66ae7ec6 (Doesn't seem to fully work, the CommandBar seems to work)
- [ ] WCT OrbitView http://playground.platform.uno/#58b3f2e0 (Implicit content is not supported error)
- [ ] WCT ScrollHeader http://playground.platform.uno/#0bbe1d12 (Librairies not supported in playground (see lines 1-2))
- [ ] WCT TileControl http://playground.platform.uno/#c793cfbe (Doesn't display the content of the TileControl)
- [ ] WCT AttachedCardShadow https://playground.platform.uno/#22447698 (Missing librairies Microsoft.Toolkit.Uwp.UI.Media and Microsoft.Toolkit.Uwp.UI)
- [ ] WCT AttachedDropShadow http://playground.platform.uno/#6fa03c37 (Missing librairies Microsoft.Toolkit.Uwp.UI.Media and Microsoft.Toolkit.Uwp.UI)
- [ ] WCT InfiniteCanvas https://playground.platform.uno/#77084457 (Not recognized by the playground altough coming from Microsoft.Toolkit.Uwp.UI.Controls)
- [ ] WCT TextToolbar http://playground.platform.uno/#cdee400d (Error due to RichEditBox (I think it's required))
- [ ] WCT CameraPreview https://playground.platform.uno/#22737c5f (Missing c# code)
- [ ] WCT RotatorTile http://playground.platform.uno/#c1886873 (Doesn't seem to work, maybe missing some code)
- [ ] WCT InAppNotification http://playground.platform.uno/#5d78273d (Missing c# code to make it work)
- [ ] WCT MetadataControl http://playground.platform.uno/#d739166d (Missing c# code to make it work)
- [x] UTU AutoLayout http://playground.platform.uno/#848c7509 (Few bugs with top options ans sliders)
- [x] UTU Chips http://playground.platform.uno/#ea42bcdc (Can't make SelectedItem attribute work or icons)
- [x] UTU TabBar https://playground.platform.uno/#95e7034b (Missing some styling)
- [ ] UTU DrawerControl https://playground.platform.uno/#924b54e2 (See Issue 206 on uno.toolkit.ui)
- [ ] UTU Card http://playground.platform.uno/#23c25178 (Doesn't display the card)
- [ ] UTU Divider https://playground.platform.uno/#a73c3a00
- [ ] UTU NavigationBar https://playground.platform.uno/#0922a98a (Missing snippet in the gallery, missing c# code)
- [ ] UTU ElevatedView https://playground.platform.uno/#ebd9f9cc (missing namespace Uno.UI.Toolkit)
- [ ] UTU CommandBar http://playground.platform.uno/#0578b7a7 (missing namespace Uno.UI.Toolkit)
- [x] MUX ColorPicker https://playground.platform.uno/#e393d6c1
- [x] MUX Expander https://playground.platform.uno/#8f34f721
- [x] MUX PagerControl https://playground.platform.uno/#739f25ee (The DisplayMode ButtonPanel doesn't work)
- [x] MUX RadioButtons https://playground.platform.uno/#a44af7fe
- [x] MUX TwoPaneView https://playground.platform.uno/#2ede6046
- [x] MUX SplitButton http://playground.platform.uno/#459cb712
- [x] MUX RadioMenuFlyoutItem https://playground.platform.uno/#0ee5b44d
- [x] MUX NavigationView https://playground.platform.uno/#9fe2421d
- [x] PersonPicture https://playground.platform.uno/#77a4a755
- [x] MUX ProgressBar/Ring https://playground.platform.uno/#e98eec25
- [ ] MUX Lottie https://playground.platform.uno/#22b155d9 (The URL doesn't work properly, considers all URL as being local).
- [x] TextBox https://playground.platform.uno/#1c590680 (Updated version)
- [x] Brush https://playground.platform.uno/#56e323ee
- [x] GridView https://playground.platform.uno/#c00868c7
- [x] Icon https://playground.platform.uno/#fab87e0b
- [x] Path https://playground.platform.uno/#214d1989
- [x] MessageDialog https://playground.platform.uno/#ea078bae (Missing c# code, but work in an actual project)
- [x] AcrylicBrush http://playground.platform.uno/#5af283fa
- [ ] Animation https://playground.platform.uno/#3e6d18c0 (Missing a lot of c# code to make the sample word that is not in the gallery code snippet)
- [ ] ItemsRepeater (See https://github.com/unoplatform/uno/discussions/8614#discussioncomment-2630886)
- [x] Examples for ItemsRepeater : 
  - https://playground.platform.uno/#1dc11e04
  - https://playground.platform.uno/#043795d8
  - https://playground.platform.uno/#54c1af47

**Comment by JulesEmond** [comment]
The issues that aren't checked are the ones that don't work at all.

**Comment by jeromelaban** [comment]
Thanks@ For lottie, can you try adding the Uno.UI.Lottie package to the playground and make a PR to see if this helps?
