### ISSUE TITLE
[Epic] Flaky tests roundup

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9080]
### Current behavior

This epic tracks flaky tests so they can be addressed one by one.

When a flaky test is added in this list, it can be set to `[Ignore]` on the platform or platforms where it tends to fail.

- [ ] `When_TextBox_Has_ContextFlyout_Keyboard_Trigger_Shows_Flyout` is flaky on iOS Skia
- [ ] `TextBox_Readonly, PasswordBox_RevealInScrollViewer and FlyoutTest_Target` are very flaky on iOS native
- [ ] `When_ReversedMouseWheel_Then_ScrollInReversedDirection` Skia X11
- [ ] `When_Nested_ScrollViewers_WheelChanged` is flaky on Skia WPF Islands
- [ ] `TextBox_TextChanging_Capitalize` is flaky on iOS
- [ ] `When_Page_Navigates_Back_With_Outer_Before` fails often on all targets in CI
- [ ] https://github.com/unoplatform/uno/issues/20731
- [ ] `When_Page_Navigates_Back_With_Outer_Before` fails often on all targets in CI
- [ ] `When_Navigate` and `When_NavigateToString` fail often on all targets in CI
- [ ] `When_Year_Mode_Shown` fails on iOS Native because the initial loading/switching between modes takes longer
- [ ] `When_FullSizeDesired` fails often on Skia Android
- [ ] `NavigationViewItem` fails in `When_Add_Remove` (`Assert.AreEqual failed. Expected:<0>. Actual:<1>. ItemsRepeater/NavigationViewItemMenuItemsHost`)
- [ ] `When_ListViewNestedAndSwipeUpThenFlickDown_Then_ScrollThenShowIndicatorButDoNotRequest` fails often on Skia Android
- [ ] `When_Focus_Immediately` fails on Skia targets
- [ ] `Given_PipsPager` is very flaky
- [ ] `When_RepeatForever_ShouldLoop` is flaky
- [ ] `When_MultipleSelectionWithoutItemClick_Then_PointersEvents` is flaky on skia targets
- [ ] `When_Large_List_Scroll_To_End_Then_Back_Up_And_First_Item` is flaky in WASM CI
- [ ] `ValidateDynamicOverflowOrderBasic()` is flaky on Android
- [ ] `When_ShapeVisual_ViewBox_Shape_Combinations` (https://github.com/unoplatform/uno/issues/18752)
- [ ] `When_Rectangle` UI test is very flaky on iOS
- [ ] `BreadcrumbBar` leak tests are flaky on iOS
- [ ] `Given_AppWindow.WhenResize` is failing in CI on Linux, passing locally
- [x] https://github.com/unoplatform/uno/issues/18375
- [x] #17101
- [x] #17102
- [ ] `When_Uri_Nullified` fails on some Skia targets
- [ ] `ValidateElementsHaveCorrectKeys` is not passing (incorrectly disabled)
- [ ] `VerifyKeyboardAcceleratorCanOverrideControlAccelerator`, `VerifyTryInvokeKeyboardAcceleratorBehaviorForLocallyScopedAccelerator`, `ValidateKeyboardAcceleratorEventNotInvokedWhenCollapsed` and `ValidateKeyboardAcceleratorBehaviorWithMultipleModifiers` on Skia are unstable
- [ ] `When_Image_Is_Monochromatic` fails on iOS .NET 9 RC1
- [ ] https://github.com/unoplatform/uno/issues/18064
- [ ] Some `Given_ImageBrush.WhenStretch` fail on iOS
- [ ] GridViewGroupedResizable is too slow and fails randomly https://github.com/unoplatform/uno/pull/18926
- [ ] https://github.com/unoplatform/uno/issues/17742
- [ ] `When_Hungarian_Culture_Column_Order`, `When_Czech_Culture_Column_Order` and `When_CanadaFrench_Culture_Column_Order` fail on net9 wasm. It could be related to a missing/filtered ICU, or a headless browser issue, it works locally.
- [ ] `MoveItemsBetweenPrimaryAndSecondaryCommands` is unstable on android
- [ ] `When_DownSampling` is flaky and disabled in https://github.com/unoplatform/uno/pull/16991
    ```
    Running test When_DownSampling()
    GLIB UNHANDLED EXCEPTIONSystem.ArgumentNullException: Value cannot be null. (Parameter 'bitmap')
       at SkiaSharp.SKImage.FromBitmap(SKBitmap bitmap)
       at Windows.UI.Composition.CompositionSurfaceBrush.UpdatePaint(SKPaint fillPaint, SKRect bounds) in C:\a\1\s\src\Uno.UI.Composition\Composition\CompositionSurfaceBrush.skia.cs:line 91
       at Windows.UI.Composition.CompositionSpriteShape.Paint(PaintingSession& session) in C:\a\1\s\src\Uno.UI.Composition\Composition\CompositionSpriteShape.skia.cs:line 19
       at Windows.UI.Composition.BorderVisual.Paint(PaintingSession& session) in C:\a\1\s\src\Uno.UI.Composition\Composition\BorderVisual.skia.cs:line 127
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 190
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.Render(PaintingSession& parentSession) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 199
       at Windows.UI.Composition.Visual.RenderRootVisual(SKSurface surface, Nullable`1 offsetOverride) in C:\a\1\s\src\Uno.UI.Composition\Composition\Visual.skia.cs:line 152
       at Uno.UI.Runtime.Skia.Gtk.SoftwareRenderSurface.OnDrawn(Context cr) in C:\a\1\s\src\Uno.UI.Runtime.Skia.Gtk\Rendering\SoftwareRenderSurface.cs:line 99
       at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
    ```
- [ ] #16167
- [ ] https://github.com/unoplatform/uno/issues/18105
- [ ] `When_UnloadAndReload_Then_ReMaterializeItems`
- [ ] `When_ThemeChange` on Wasm    
    ![image](https://github.com/unoplatform/uno/assets/31348972/d891d36c-6d83-43f8-b04c-0b97c5bda12d)
- [ ] Android `TestProgressRing_InitialState` fails
- [ ] `FlyoutTest_Unloaded`
- [ ] `FlyoutTest_Target` is flaky on iOS
- [x] https://github.com/unoplatform/uno/issues/13417
- [ ] `PasswordBox_RevealInScrollViewer` is flaky on iOS
- [x] #15734
- [ ] TextBox_VerticalAlignment is flaky on Wasm
- [ ] `Verify_MenuBarItem_Bounds_Native_Popups` is flaky on Android - started being flaky after pull request #13630 (@ramezgerges)
- [ ] `TextBox_Readonly` is flaky on iOS
- [ ] `When_Drag_Then_DoesNotScroll` is not working on Android, the thumb drags when it should not
- [ ] `CanChangeDisplayModeBeforeLoaded` is flaky on Skia
- [ ] `Holding_Tests.When_InListViewWithoutItemClick` fails for missing item on android
- [ ] `Holding_Tests.When_Basic` fails on android
- [ ] `Holding_Tests.When_InScroll` fails on android
- [ ] `Holding_Tests.When_InListViewWithItemClick` fails on android
- [ ] `TestTextBoxReleaseOutFocused` is flaky on WASM
- [x] https://github.com/unoplatform/uno/issues/15829
- [ ] `When_MultipleItems` is not failing sometimes (Timing related ?)
- [ ] `Flyout_TemplatedParent` is flaky on WASM
- [ ] https://github.com/unoplatform/uno/issues/15828
- [ ] https://github.com/unoplatform/uno/issues/15471
- [ ] `TestTranslatedTap` is flaky on WASM (could be related to https://github.com/unoplatform/uno/issues/13844)
- [ ] `ValidateOverflowPlacement` does not pass on Android
- [ ] `TestTranslatedTap` is failing on android
- [ ] `DoesNotShowMenuIfSecondaryElementsAreCollapsed` does not pass on Android
- [ ] `When_NestedInSVAndOutOfViewportOnInitialLoad_Then_MaterializedEvenWhenScrollingOnMinorAxis` is flaky on WASM
- [ ] #13844
- [ ] Android `When_NestedIRSlowlyChangeViewport_Then_MaterializedNeededItems` (Timeout even with retries) (Youssef: Can't repro)
- [ ] Android `When_Verify_Canvas_With_Outer_Clip` (`Assert.Fail failed. ImageAssert.HasColorAt @ line 73`) (Youssef: Verified - it always fails)
- [ ] `UITests.Windows_UI_Xaml_Media.GradientBrushTests.GradientsPage` crashes the android emulator completely (not just the app)
- [ ] Android `VerifyNavigationViewItemToolTipPaneDisplayMode` (Youssef: Verified - it always crashes locally)
- [ ] When_Focused_Element_Transformed is crashing the iOS/Android emulator
- [ ] Android `VerifyCollectionChangeGetsRespected` (Cleanup `System.Exception: Event was not raised.` in `MUXApiTestBase.Cleanup()`) (Youssef: test not disabled on master, and always passes for me)
- [ ] `ListView_ObservableCollection_Unused_Space` fails regularly on iOS (`Expected: 132.0f  But was:  88.0f`)
- [ ] `When_Open_Close_Root_Twice_Keep_State` fails on android for missing TreeView items (Youssef: fails locally with null ref)
- [ ] `When_UsingMultipleLanguages` unit test fails when running with net7 or later (DateFormatter is buggy and CultureInfo itself returns wrong values)
- [ ] https://github.com/unoplatform/uno/issues/11997
- [x] https://github.com/unoplatform/uno/issues/13257
- [ ] `When_Grid_RowCollection_Changes` fails with invalid `child.SizePassedToArrangeOverride`
- iOS 16+ tests
   - [ ] `NativeCommandBar_Size` fails (The first orientation change fails to be applied)
   - [ ] `ListView_SelectedItems` fails (Timeout ?)
   - [ ] `When_Flipview_DataTemplateSelector` (`AssertFailedException: Assert.Fail failed. ImageAssert.HasColorAt @ line 101`)
   - [ ] `When_Add_Remove` failure: `ColorPicker`
   - [ ] `When_Add_Remove` failure: `CalendarView`
- [ ] iOS `When_ItemsControl.When_NestedItemsControl_RecycleTemplate` (`Assert.AreEqual failed. Expected a difference no greater than &lt;1&gt; between expected value &lt;50&gt; and actual value &lt;0&gt;. `)
- [ ] iOS `RepeaterTests.VerifyCorrectionsInNonScrollableDirection`
- [ ] iOS/Skia `VerifyFocusedItemIsRecycledOnCollectionReset` (Skia fixed in https://github.com/unoplatform/uno/pull/13074)
- [ ] iOS `When_WebMessageReceived` (`Timed out waiting for condition to be met. When_WebMessageReceived():207`)
- [ ] iOS `When_Flipview_Items_Modified` (`Timed out waiting for equality condition to be met. Expected -1 but last received value was 0.`)
- [ ] iOS `When_Render_Border_GetPixelsAsync` (`Assert.AreEqual failed. Expected:&lt;&lt;10, 10&gt;&gt;. Actual:&lt;&lt;10.5, 10&gt;&gt;. Invalid Layouted.`)
- [x] https://github.com/unoplatform/uno/issues/13095
- [ ] [All platforms] `ValidateFractionalWidthDoesNotCrash` (`Assert.Fail failed. Timeout waiting on SpectrumRectangle.Fill to be set.`) (Youssef: Test is actually skipped in WinUI. There is not much info on why it's skipped there, but I don't see anything that should trigger property changed for Fill)
- [ ] `When_StretchAndAlignment` on Android 28 (Youssef: Passing for me locally)
- [ ] `TextBox_Readonly_ShouldNotBringUpKeyboard` on Android 30 (The keyboard does not show up on emulators, breaking the test)
- [ ] `When_PressOnContainerAndReleaseOnNested_Mouse` on WASM (fails in CI)
- [ ] `When_RepeatDuration`: It was enabled in https://github.com/unoplatform/uno/pull/13060, but then failures are found and reverted in https://github.com/unoplatform/uno/pull/13089
- [ ] https://github.com/unoplatform/uno/issues/13384
- [ ] [iOS/Skia/macOS] `RepeaterTests.VerifyRepeaterDoesNotLeakItemContainers` (Skia started failing in https://github.com/unoplatform/uno/pull/16523)

### In Progress

- [x] `TestTextBoxReleaseOutFocused` is flaky on WASM
- [x] `TestTextBoxTap` is very flaky on WASM
- [ ] `Given_SymbolIcon.Validate_Size` fails on all targets (`Expected:&lt;20&gt;. Actual:&lt;627.5&gt;`) (https://github.com/unoplatform/uno/pull/13069)
- [x] Android `VerifyDropdownItemTemplateWithNoControl` (failed cleanup `System.Exception: Event was not raised.`) (Youssef: passing for me - https://github.com/unoplatform/uno/pull/13077)
- [x] Android `VerifyBreadcrumbDefaultAPIValues` (failed cleanup `System.Exception: Event was not raised.`) (Youssef: passing for me - https://github.com/unoplatform/uno/pull/13077)
- [x] `ValidateOverflowButtonHidesWhenAppropriateWithNoAppBarButtons`, `ValidateMoreButtonCanShowWithoutSizeChanging`, `ValidateOverflowButtonHidesWhenAppropriateWithPrimaryAppBarButtons` are failing randomly on android. (Youssef: passing for me - https://github.com/unoplatform/uno/pull/13078)
- [x] Android/iOS `When_EmbeddedResource` (resource is not included when build on `dotnet build`) (Youssef: This appears to only be an issue for Uno.UI solution, ie, not a problem for external customers. Fixing in https://github.com/unoplatform/uno/pull/13079)
- [x] `DoubleAnimation_Tests` on android. These tests fail on android when running one by one, but don't when run with others. (Youssef: Can't repro. Enabling in #13082)
   ```
   System.Exception : Error while performing WaitFor([unknown], "Failed to find [Completed] on [Text]", null, null, null)
  ----> System.TimeoutException : Failed to find [Completed] on [Text]
  ```
- [x] `When_Opacity_Paused_With_FillBehaviorHold_Then_Hold` - on Android (Youssef: Can't repro. Enabling in #13082)
- [x] `When_Transforms_Paused_With_FillBehaviorStop_Then_Hold`. This test tends to fail when run alone, indicating a race condition, see in the comments for screenshots of the test. (Youssef: Can't repro. Enabling in #13082)
   ```
   1) Failed : SamplesApp.UITests.Windows_UI_Xaml_Media_Animation.DoubleAnimation_Tests.When_Transforms_Paused_With_FillBehaviorStop_Then_Hold
   ImageAssert.AreEqual @ line 85
   pixelTolerance: No color tolerance
   expected: Initial (When_Transforms_Paused_With_FillBehaviorStop_Then_Hold_Initial.png {Width=1280, Height=800}) in 
   {X=615,Y=442,Width=50,Height=50}
   actual  : Final (When_Transforms_Paused_With_FillBehaviorStop_Then_Hold_Final.png {Width=1280, Height=800}) in 
   {X=615,Y=442,Width=50,Height=50}
   ```
- [x] iOS/Android `Given_ImageBrushStretch` (Incorrect `RenderTargetBitmap` content) (youssef: Issue not related to RenderTargetBitmap. Fixing test in https://github.com/unoplatform/uno/pull/13081)

### Done

- [x] https://github.com/unoplatform/uno/issues/10164
- [x] Android all `Basics_AutomatedTransformation` (` The specified child already has a parent. You must call removeView() on the child&#39;s parent first.`) (https://github.com/unoplatform/uno/pull/13061)
- [x] Android/Skia `When_Render_Then_CanRenderOnCanvas` (Assert.Fail failed. ImageAssert.HasColorAt @ line 134) (works locally on Skia, fails on Android and being fixed in https://github.com/unoplatform/uno/pull/13070)
- [x] Wasm `When_Reorder_To_Last_2` (https://github.com/unoplatform/uno/pull/13093)
- [x] [All platforms] `RepeaterTests.VerifyUIElementsInItemsSource` (https://github.com/unoplatform/uno/pull/13074)
- [x] [All platforms] `RepeaterTests.NestedRepeaterWithDataTemplateScenario` (https://github.com/unoplatform/uno/pull/13074)
- [x] [All platforms] `RepeaterTests.VerifyStoreScenarioCache` (https://github.com/unoplatform/uno/pull/13074)
- [x] https://github.com/unoplatform/uno/issues/10165 (https://github.com/unoplatform/uno/pull/13056)
- [x] https://github.com/unoplatform/uno/pull/13071

**Comment by Youssef1313** [comment]
> `When_Reorder_To_Last_2` on WASM, Android

This test appears to be Wasm only. I'm disabling in https://github.com/unoplatform/uno/pull/9571

**Comment by jeromelaban** [comment]
Images for When_Transforms_Paused_With_FillBehaviorStop_Then_Hold:

Teardown:
![When_Transforms_Paused_With_FillBehaviorStop_Then_Hold_When_Transforms_Paused_With_FillBehaviorStop_Then_Hold_-_Tear_down_on_error](https://user-images.githubusercontent.com/5839577/199139353-7aff9fb0-9d23-4cbd-aff5-0b3c90493ff9.png)
Initial:
![When_Transforms_Paused_With_FillBehaviorStop_Then_Hold_Initial](https://user-images.githubusercontent.com/5839577/199139354-bf702d9c-a974-4497-b4f1-681b86c30c2c.png)
Final:
![When_Transforms_Paused_With_FillBehaviorStop_Then_Hold_Final](https://user-images.githubusercontent.com/5839577/199139355-b08afe08-d49c-4080-9720-1b609478fe28.png)

**Comment by ramezgerges** [comment]
`When_UsingMultipleLanguages` is acting really off. First off, `CultureInfo` returns weird patterns e.g. in ft-CA, `info.LongTimePattern` returns `HH 'h' mm` instead of `HH:mm`. A possible hack is to replace the added garbage with a colon e.g. using `Regex.Replace(value, " '[^']*' ", ":")`, but obviously, that isn't ideal. Another thing is that our `DateTimeFormatter` implementation diverges a lot from the net7 implementation, so it might need a rewrite or something.

**Comment by ramezgerges** [comment]
`VerifyFocusedItemIsRecycledOnCollectionReset` seems to fail on skia due to a problem with dispatching measure/arrange. Items in an `ItemsRepeater` are only updated in a `Measure`, and it appears that no `Measure` is dispatched during the test (even though some paths are dirty for sure). A manual `GetRoot(repeater).Measure(Window.Current.Bounds.Size)` (where GetRoot just walks up the tree to get the RootVisual) passes the test, but I've failed to find the root of the problem.

**Comment by Youssef1313** [comment]
I took a look at `When_EmbeddedResource`, I think the problem is related to shared projects.

![image](https://github.com/unoplatform/uno/assets/31348972/4d07c02a-c125-4cc1-9560-88d88508c7ee)

The `TargetPath` here is `SharedProjectEmbeddedFile.txt` instead of `Embedded/SubFolder1/SubFolder2/SharedProjectEmbeddedFile.txt`.

**Comment by Youssef1313** [comment]
`AssignLinkMetadata` is somehow capable of determining the Link correctly. It should have run before `AssignTargetPath`

**Comment by MartinZikmund** [comment]
- [ ] `When_WebMessageReceived_After_RemoveAdd` fails constantly on Native Android and Native iOS

**Comment by MartinZikmund** [comment]
# Repro generator

This issue was classified as not reproducible with a code sample or test.

**Reason:** Epic tracking flaky tests.

**Comment by MartinZikmund** [comment]
## Flaky tests disabled (2026-04-10)

The following tests have been disabled on branch `dev/mazi/flaky-disable` based on analysis of the last 5 master CI builds (206436, 206398, 206296, 206235, 206121):

### iOS Native
- `SamplesApp.UITests.UnoSamples_Tests.TextBox_TextChanging_Limit` — `[Ignore]`
- `SamplesApp.UITests.Windows_UI_Xaml_Controls.ButtonTests.UnoSamples_Test_Button_Click.Button_Events` — `[Ignore]`
- `SamplesApp.UITests.Windows_UI_Xaml_Controls.ListViewTests.ListView_ObservableCollection_Creation_Count` — `[Ignore]`
- `SamplesApp.UITests.Windows_UI_Xaml_Controls.ListViewTests.ListView_SelectedItems` — `[Ignore]` (broadened from UIKit-only)

### iOS Skia
- `Windows.UI.Tests.Enterprise.CommandBarIntegrationTests.ValidateOverflowScrollViewerDoesNotScrollWithArrowKeys` — added `RuntimeTestPlatforms.SkiaIOS` to `PlatformCondition` exclude
- `Given_WebView2.When_Navigate_Unsupported_Scheme` — added `RuntimeTestPlatforms.SkiaIOS` to `PlatformCondition` exclude

### Android Native
- `Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_RadioButton.When_RadioButtons_Unload_SelectedIndex` — `[Ignore]`
- `Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_RadioButton.When_RadioButtons_Unload_SelectedItem` — `[Ignore]`

### Wasm Native
- `SamplesApp.UITests.Windows_UI_Xaml_Controls.BorderTests.Check_CornerRadius_Border_Basic` — `[Ignore]`

### Not disabled (infrastructure issues, not test code)
- Wasm Native Snapshot Tests — consistently broken due to chromedriver/Node.js version incompatibility
- iOS Native/Skia agent disconnections — macOS hosted agent instability

**Comment by MartinZikmund** [comment]
## Flaky tests disabled (2026-04-16)

### Skia WASM
- `Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Controls.Given_TextBox_ContextMenuPosition.When_TextBox_Has_ContextFlyout_Keyboard_Trigger_Shows_Flyout` — added `RuntimeTestPlatforms.SkiaWasm` to existing `PlatformCondition` exclude (was `SkiaIOS` only).

**Comment by MartinZikmund** [comment]
Disabled the following flaky runtime tests on their affected targets via `PlatformCondition` on branch `dev/mazi/skia-test-stability` (commit a70c782183), pending root-cause fixes:

| Test | Disabled on |
|------|-------------|
| `Given_TextBlock.When_IsTextSelectionEnabled_ContextMenu_SelectAll` | Skia X11 (Linux) + Framebuffer |
| `Given_ScrollViewer.When_Nested_ScrollViewers_WheelChanged` | Skia WASM |
| `Given_TextBox.When_Chunk_DoubleTapHeld` | Skia WASM |
| `Given_TextBox.When_BeforeTextChanging_Resets_Selection_Direction` | Skia WASM |
| `Given_ComboBox.When_ComboBox_ScrollIntoView_SelectedItem` / `When_ComboBox_ScrollIntoView_SelectedIndex` | Skia WASM |
| `Given_InteractionTracker.When_TryUpdatePositionWithAdditionalVelocity_TwoCalls` | Skia iOS |
| `Given_ListViewBase.When_SmallExtent_And_Large_List_Scroll_To_End_And_Back_Half_Size` | all Skia targets (especially flaky) |

Root-cause notes for follow-up:
- **TextBox WASM backward-selection** (`When_Chunk_DoubleTapHeld`, `When_BeforeTextChanging_Resets_Selection_Direction`): the managed selection direction (`IsBackwardSelection`) is overwritten by the asynchronous `selectionchange` round-trip through the hidden native `<input>` element on WASM, so the backward selection is not reliably established under injected input.
- **ScrollViewer nested wheel** (`When_Nested_ScrollViewers_WheelChanged`): injected wheel input does not scroll the inner ScrollViewer all the way to its bottom on WASM (it stops short), so the offset never reaches `ScrollableHeight`.
- **InteractionTracker** (`When_TryUpdatePositionWithAdditionalVelocity_TwoCalls`): per-platform floating-point divergence of the inertia resting position on iOS vs the exact-string assertion.
- **ComboBox ScrollIntoView**: on WASM the selected container is not realized AND scrolled fully into the viewport within the timeout.
- **ListViewBase `When_SmallExtent_And_Large_List_Scroll_To_End_And_Back_Half_Size`**: especially flaky across all Skia targets.

**Comment by MartinZikmund** [comment]
## Triage note: the recent CI red is mostly *not* flaky tests

I swept the last 200 `Uno.UI - CI` builds (2026-09-02 → 09-09; 121 of 200 red, master 0/24 green) looking for tests to add here. Almost nothing qualified, and the reasons are worth recording so the next person doesn't repeat the analysis.

### Only ~8% of the red is attributable to tests

Of 131 failed/partial builds, **10** were red *solely* because a test failed. 53 carry a test-failure row at all, but 43 of those also carry an infrastructure or build failure that would have reddened them anyway. The dominant causes were job timeouts (44 builds / 30 branches), PR compile errors (16), the public-API gate (11), and a single 100%-broken iOS TestFlight publish job (16 builds, all master).

So: adding the worst-looking test names here would have recovered almost no green, while hiding several things that should stay visible.

### Three counting traps that make the CI look far flakier than it is

Anyone mining failed-test names from ADO logs will hit these. All three inflate or invert the apparent flake rate:

1. **iOS prints the failed-test list twice.** `build/test-scripts/ios-uitest-run.sh` calls `dotnet run list-failed` at both line 479 and line 488, against two paths holding the same results. tvOS (`tvos-uitest-run.sh:299`), Android (`:212`) and WASM (`:143`) call it once. Any "did it fail again on the retry?" metric keyed on duplicate rows reads ~97% on iOS and 0% on tvOS — pure log formatting, unrelated to test health.
2. **The task name `Run Runtime Tests` is used by three separate desktop stages** (Windows, Linux, Linux Framebuffer). Key on the timeline record id, not the display name, or one test failing across stages in one build collides into a fake "repeat offender".
3. **`record['log']['id']` only reaches the latest job attempt.** Earlier attempts hang off `previousAttempts[].timelineId`. For any retried job you get the *filtered rerun's* list, not the original failure set.

Also: build volume is very uneven (106 of those 200 builds finished on 2026-09-03 alone), and jobs that publish no results at all — an Android job hard-killed at the cap, a WASM shard hitting UNOBLD005 — contribute **zero** rows, so the denominator understates the problem. Normalise before quoting any rate.

### What the corrected data actually says

The tests that looked worst were mostly *not* flaky:

- **~126 tvOS `Given_TextBox.*` / `KeyboardAccelerator` failures** come from exactly two unmerged PR branches and are green on every master build in the window. They are catching real tvOS text-input regressions. Filing them here would green-light both.
- **A 20-test iOS cluster** (MenuFlyout, theme resolution, ComboBox, TabView, TreeView) fails **all-or-nothing** across four unrelated branches — one shared run-scoped state corruption, not 20 flakes. Disabling them removes the only symptom.
- **`Given_InputPane.When_Focused_Element_Not_Occluded_Then_Centered_Content_Is_Not_Moved`** is the one test that repeatedly reds builds on its own (17 builds / 12 branches). It *is* genuinely intermittent — it fails attempts 1 and 2 and passes on 3, hidden by `UnitTestEngineConfig.DefaultRepeatCount = 3` — but it guards a just-shipped `ScrollContentPresenter` arrange change and may be catching a real extra layout pass on every keyboard show. It reproduces on Skia Desktop, so it is worth debugging rather than listing here.

### Two infrastructure defects that make flakiness unmeasurable

Both are being fixed separately; noting them here because they explain missing data in this epic:

- **The runtime-test watchdog could never fire.** `END_TIME=$((SECONDS+TIMEOUT))` charged the emulator/simulator boot and install twice, putting the deadline past the ADO job cap — 44 Android runs were hard-killed at exactly 44.5 minutes, publishing no logs and no failed-test list, so none of their failures ever reached this epic.
- **The test engine has no default per-test timeout.** `UnitTestsControl.GetTestTimeout` only reads an explicit `[Timeout]` attribute, and the else branch is a bare `await task`. One hung test with no attribute discards up to 1747 already-passing results *and* every failing test name.

### Housekeeping

`When_Page_Navigates_Back_With_Outer_Before` is listed twice in the checklist above.

**Comment by MartinZikmund** [comment]
Two more, on **Skia Android**, now excluded there and tracked by #24480:

- [ ] `Given_AutoSuggestBox.When_Popup_Above` — popup placement asserted before the suggestion list settles on its final height (4 failures across 4 distinct branches, incl. `master`)
- [ ] `Given_TextBox.When_Touch_Focused_Then_Scrolled_Away_The_Scroll_Sticks` — injected drag only partly reaches the ScrollViewer, 37px of a 200px drag (10 failures across 7 distinct branches, incl. `master`)

Ranked by distinct source branch over the 191 CI builds that ran the Android leg between 2026-09-02 and 2026-09-10, so a re-queued red branch cannot fake a cluster. These are the top two named failures on that leg.

**Comment by MartinZikmund** [comment]
Four more, now disabled on **all targets** by #24491 and tracked by #24489:

- [ ] `Given_InputPane.When_Focused_TextBox_Has_Content_Below_Then_Scrolled_Above_Occlusion` — setup scrolls to a content offset computed from the live viewport height, so the intended geometry only holds for a band of window sizes
- [ ] `Given_InputPane.When_Focused_Element_Not_Occluded_Then_Centered_Content_Is_Not_Moved` — `0.5` tolerance on `TransformToVisual` positions; a centered card can legitimately shift half a pixel when the pad changes the extent's parity
- [ ] `Given_InputPane.When_Occluded_Field_In_Viewport_Sized_Content_Then_Scrolled_Above_Occlusion` — 40px "minimal scroll" upper bound with no slack for a layout pass landing one scroll line further
- [ ] `Given_ScrollViewer_ScrollChaining.When_Chaining_Backwards_Then_Residual_Chains_To_Outer` — chains twice and reads the public offsets after a single `WaitForIdle`, while they are refreshed through `RequestUpdate`

All four are hypotheses from reading the tests, not measured root causes — details in #24489.

**Comment by MartinZikmund** [comment]
One more in the same PR (#24491), also tracked by #24489 — this one excluded only on **Skia iOS / Skia tvOS**, not everywhere:

- [ ] `Given_BitmapIcon.When_Foreground_Changed_With_ShowAsMonochrome_True` — screenshot-based tint assert after a single `WaitForIdle`, no retry; not analysed

Note for anyone disabling this test further: it already carries a conditional `[Ignore]` for non-Skia and non-`RenderTargetBitmap` targets, and `IgnoreAttribute` is `AllowMultiple = false`, so a second `[Ignore]` on it is a compile error — use `[PlatformCondition]` or an `#else` arm instead.
