### ISSUE TITLE
Restore failing macOS runtime tests

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9282]
## What would you like to be added:

Many runtime tests are disabled on macOS as they are either failing or crashing the app.

## Why is this needed:

Search for `#9282` or `#if __MACOS__` in `Uno.UI.RuntimeTests` project. Remove `[Ignore]` and fix the tests.

Search for `#9282!` for critical tests that should be fixed soon.

List from #626:
- [ ] When_GetAllKeys
- [ ] When_IsSuppressEnabled
- [ ] When_Has_ColumnSpacing
- [ ] Test_Flyout_Binding
- [ ] Test_Flyout_Binding_In_MenuFlyoutItem
- [ ] Test_Flyout_Binding_With_SetAttachedFlyout
- [ ] Check_Single_Character_Run_With_Wrapping_Constrained

## Notes for contributors

Some of the tests might be quite easy to fix, so fixing some can be a good first issue.

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
